print("Welcome to Tip calculator!")
bill = float(input("What was your total bill: "))
tip = float(input("What % tip would you like to give? 10,12 or 15?: "))
people = int(input("How many people to split in? "))
tip_all = bill*(tip/100)
final = round((tip_all+bill)/people,2)
print(f"Each person should pay: {final}")